name: A workflow for fibonacci action
on: [push,pull_request]

jobs:
  build:
    name: Run the Fibonacci action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./fibonacci
        with:
          N_INDEX: 12